### ISSUE TITLE
Vision of the port

### ISSUE THREAD

**Issue by sskras** [sux2mfgj/bitvisor-armv8#7]
Hello

nice project! Is the changes going to merge back into the main BitVisor repository?
Or maybe you have no idea yet?

**Comment by sux2mfgj** [comment]
Hi sskras,

Thank you for your comment.

This project is just for test, so there is no the plan to merge back this changes.
I‘m sorry I failed you.

**Comment by sskras** [comment]
No at all ! : )

Thanks for keeping modification open. Whoever wants the ARM port, will have the starting point. Cheers!
